name: reactive_data_manager
description: "Sync data across the app"
version: 1.0.0
homepage:
repository: https://github.com/Nazarovv676/reactive-data-manager

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
